installation of mongodb for linux added to readMe
scorelab/Stackle pull request #150
Opened 2018-10-21 08:11 UTC by war-turtle

### Fixes #149 
## installation of mongodb for debian based system added to readMe

2018-10-21 09:08 UTC, monalshadi reviewed
You can as well include steps for other distros of linux. :+1:

2018-10-21 09:17 UTC, matosBrent requested changes
Please check comments

2018-10-21 09:17 UTC, matosBrent commented on README.md
> +1. sudo apt-get update
Added commands between backtick.

2018-10-21 09:17 UTC, matosBrent commented on README.md
>  3. Once all the packages are installed run `npm start`
End this line with a fullstop.

2018-10-21 09:17 UTC, matosBrent commented on README.md
> +    ```
add language tag after triple backticks. 
For eg: ```sh for shell

2018-10-21 09:17 UTC, matosBrent commented on README.md
> +-   MongoDB is used as the databases for storing data related to stackle
End each point with a full stop

2018-10-21 09:17 UTC, matosBrent commented on README.md
>  ![Architecture](./stackle_app/app/images/architecture.jpg)
The image src is not working. Please check

2018-10-21 20:07 UTC, war-turtle commented
Done Requested Changes But can't find the missing image in the whole project

2018-11-28 15:09 UTC, dinaelhanan commented
I used a link on my PR instead of outlining all the steps since that will 
a) avoid any errors / allow users to follow more thorough distro-specific instructions
b) reduce the space taken up by the README.md file, although that isn't that big of an issue, it helps in the long run

2019-02-08 02:09 UTC, psnmissaka approved these changes

2021-11-26 06:30 UTC, closed without merging